### ISSUE TITLE
dimensionless power spectrum

### ISSUE THREAD

**Issue by joellebegin** [joellebegin/Power-Spectra#16]
have changed the way I compute the dimensionless power spectrum (\Delta^2) by multiplying by k**3 before binning. Still unsure about: 

- should I multiply by k**3 _before_ taking the complex magnitude squared? Right now, I'm multiplying the amplitude squared by k**3.

- should I divide by 2pi before binning?

**Comment by acliu** [comment]
Answer to the first question: it's totally fine to multiply after taking the complex magnitude squared. The key is that we want to avoid binning artifacts. Whether you do the multiplication before or after taking the magnitude, you still have the fine k-space resolution. (Plus it'd be weird to do it before squaring...you'd have to multiply by k**1.5).

Answer to the question: doesn't matter. Do it after. Since it's just dividing by a single number, it won't matter and you will save computation time if you do it after.

**Comment by joellebegin** [comment]
Perfect!
